name: "Build"
# description: Build and test simeng on various OS with various compilers followed by benchmarking and a performance regression test followed by a clang format if all previous workflow succeed

on:
  workflow_dispatch:

#  workflow_call:
#  push:
#     branches:
#       - dev

  pull_request:
    branches:
      - dev
      - main


#  schedule:
#    - cron: '0 0 */6 * *'  # Runs every 6 days
  
jobs:

  ###################################
  # Debug Mode
  ###################################
  DEBUG_LINUX:
    name: "Debug - build and test"
    uses: ./.github/workflows/LINUX_BUILD_TEST.yml
    with:
      RUNNER: ubuntu-latest
      SIMENG-MODE: Debug
    secrets: inherit

  DEBUG_MACOS:
    name: "Debug - build and test"
    uses: ./.github/workflows/MACOS_BUILD_TEST.yml
    with:
      SIMENG-MODE: Debug
    secrets: inherit

  ##################################
  # Release Mode
  ##################################
  RELEASE_LINUX:
    name: "Release - build, test and benchmarks"
    uses: ./.github/workflows/LINUX_BUILD_TEST.yml
    with:
      RUNNER: ubuntu-latest
      SIMENG-MODE: Release
    secrets: inherit

  RELEASE_MACOS:
    name: "Release - build, test and benchmarks"
    uses: ./.github/workflows/MACOS_BUILD_TEST.yml
    with:
      SIMENG-MODE: Release
    secrets: inherit


